version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 11111
      POSTGRES_USER: olga
      POSTGRES_DB: olga

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

