version: '3.1'

services:

  dbOlga:
    image: postgres:latest

    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      POSTGRES_USER: app
      POSTGRES_DB: app




